### ISSUE TITLE
running imagemol on gpu

### ISSUE THREAD

**Issue by SoodabehGhaffari** [HongxinXiang/ImageMol#17]
Hello,
I am having difficulty running Imagemol on GPU. Here are my slurm job and the error that I get:

I appreciate your help.

Best Regards
Soo

#!/bin/bash
#SBATCH --job-name=test 
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=4        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=4G         # memory per cpu-core (4G is default)
#SBATCH --time=72:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --[mail-user=sg6615@princeton.edu](mailto:mail-user=sg6615@princeton.edu)
#SBATCH -o ./classification/test_logs/gpu_testing.out
#SBATCH -p cryoem
#SBATCH --gres=gpu:1             # number of gpus per node 

module purge
module load anaconda3/2023.3
#conda activate imagemol
#module load cudatoolkit/11.7
#module load nvhpc/22.5
conda activate gpu-imagemol

python ../finetune_gpu.py --gpu 1 --ngpu 1 --save_finetune_ckpt 1 --log_dir ./classification/test_logs --dataroot /scratch/gpfs/sg6615/ImageMol/final_data --dataset classification --task_type classification --resume /scratch/gpfs/sg6615/ImageMol/pretrain_model/ImageMol.pth.tar --image_aug --lr 0.5 --batch 8 --epochs 10 --split random

/scratch/gpfs/sg6615/CONDA/envs/gpu-imagemol/lib/python3.7/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: [libtorch_cuda_cu.so](https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Flibtorch_cuda_cu.so%2F&data=05%7C02%7Csoodabeh%40princeton.edu%7Cf592589d17a24706877f08dc28109b56%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638429298994403022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ytb1%2BvS%2FnukonhZ08sbgJjHLExa4aBwMx6XIkSff0Mw%3D&reserved=0): cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "../finetune_gpu.py", line 10, in <module>
    import torchvision.transforms as transforms
  File "/scratch/gpfs/sg6615/CONDA/envs/gpu-imagemol/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/scratch/gpfs/sg6615/CONDA/envs/gpu-imagemol/lib/python3.7/site-packages/torchvision/models/__init__.py", line 17, in <module>
    from . import detection, optical_flow, quantization, segmentation, video
  File "/scratch/gpfs/sg6615/CONDA/envs/gpu-imagemol/lib/python3.7/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/scratch/gpfs/sg6615/CONDA/envs/gpu-imagemol/lib/python3.7/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/scratch/gpfs/sg6615/CONDA/envs/gpu-imagemol/lib/python3.7/site-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in <module>
    from torch.ao.quantization import DeQuantStub, QuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/scratch/gpfs/sg6615/CONDA/envs/gpu-imagemol/lib/python3.7/site-packages/torch/ao/quantization/__init__.py)

**Comment by Xnightwish** [comment]
Hello, have you successfully run the code for this pre-trained model?
